project/Django_Blog/djangonautic/accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
	path('signup/',views.signup_view,name='signup'),
	path('login/',views.login_view,name='login'),
	path('logout/',views.logout_view,name='logout'),
]

project/Django_Blog/djangonautic/articles/urls.py
from django.urls import path
from . import views		# importing views.py from the same directory


app_name='articles'

urlpatterns = [
    path('', views.article_list,name='list'),
   	path('create/',views.article_create,name='create'),
    path('<slug:slug>/', views.article_detail,name='detail')
]

project/Django_Blog/djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),	#registering the urls of the articles app
    path('',article_views.article_list,name="HOME")				#url route which sends home function from views.py
]


urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project/Django_Blog/djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
	title=models.CharField(max_length=100)
	slug=models.SlugField()
	body=models.TextField()
	date=models.DateTimeField(auto_now_add=True)
	thumb=models.ImageField(default='default.png',blank=True)
	author=models.ForeignKey(User,default=None,on_delete=models.DO_NOTHING)


	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50]+"...."

project/Django_Blog/djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model=models.Article
		fields=['title','body','slug','thumb']

project/Django_Blog/djangonautic/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
	if request.method=="POST":
		form=UserCreationForm(request.POST)
		if form.is_valid():
			user=form.save()
			login(request,user)
			return redirect('articles:list')
	else:
		form=UserCreationForm()
	return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
	if request.method=='POST':
		form=AuthenticationForm(data=request.POST)
		if form.is_valid():
			user=form.get_user()
			login(request,user)
			if 'next' in request.POST:
				return redirect(request.POST.get("next"))
			else:
				return redirect("articles:list")
	else:
		form=AuthenticationForm()
		
	return render(request,'accounts/login_form.html',{"form":form})

def logout_view(request):
	if request.method=='POST':
		logout(request)
		return redirect('articles:list')

project/Django_Blog/djangonautic/articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
	articles=Article.objects.all().order_by("date")
	return render(request,"articles/article_list.html",{'articles':articles})

def article_detail(request,slug):
	# return HttpResponse(slug)
	article=Article.objects.get(slug=slug)
	return render(request,"articles/article_details.html",{"articles":article})

@login_required(login_url='/accounts/login/')
def article_create(request):
	if request.method=='POST':
		form=forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			instance=form.save(commit=False)
			instance.author=request.user
			instance.save()
			return redirect('articles:list')
	else:
		form=forms.CreateArticle()
	return render(request,'articles/article_create.html',{'form':form})

project/Django_Blog/djangonautic/accounts/templates/accounts/login_form.html
{%extends 'base_template.html'%}

{%block content%}
	<h1>login</h1>
	<form class="site-form" action="{%url 'accounts:login'%}" method="post">
		{%csrf_token%}
		{{form}}
		{%if request.GET.next%}
			<input type="hidden" name="next" value="{{request.GET.next}}">
		{%endif%}
		<input type="submit" name="login">
	</form>
	<p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{%endblock%}

project/Django_Blog/djangonautic/accounts/templates/accounts/signup.html
{%extends 'base_template.html'%}

{%block content%}
	<h1>signup</h1>
	<form class="site-form" action="/accounts/signup/" method="post">
		{%csrf_token%}
		{{form}}
		<input type="submit" name="Singup">
	</form>
{%endblock%}

project/Django_Blog/djangonautic/articles/templates/articles/article_create.html
{%extends 'base_template.html'%}

{%block content%}
<div class="create-article">
	<h2>create an awesome new article</h2>
	<form class="site-form" action="{%url 'articles:create'%}" method="post" enctype="mutipart/form">
		{%csrf_token%}
		{{form}}
		<input type="submit" name="Create">
	</form>
</div>
{%endblock%}

project/Django_Blog/djangonautic/articles/templates/articles/article_details.html
{% extends 'base_template.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ articles.thumb.url }}" />
        <h2>{{ articles.title }}</h2>
        <h3>Written by {{ articles.author.username }}</h3>
        <p>{{ articles.body }}</p>
        <p>{{ articles.date }}</p>
    </div>
</div>
{% endblock %}

project/Django_Blog/djangonautic/articles/templates/articles/article_list.html
{%extends 'base_template.html'%}

{%block content%}
	<h1>Article Lists</h1>
	<div class="articles">
		{%for article in articles%}
		<div class="article"></div>
			<h2><a href="{%url 'articles:detail' slug=article.slug%}">{{article.title}}</a></h2>
			<p>{{article.snippet}}</p>
			<p>{{article.date}}</p>
			<p class="author">added by {{article.author.username}}</p>
		</div>
		{%endfor%}
	</div>
{%endblock%}

project/Django_Blog/djangonautic/templates/aboutpage.html
<!DOCTYPE html>
<html>
<head>
	<title>ABOUT</title>
</head>
<body>
	<h1>About Us</h1>
	<p>We like djago</p>

</body>
</html>

project/Django_Blog/djangonautic/templates/base_template.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'HOME' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

project/Django_Blog/djangonautic/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>HOME</title>
</head>
<body>
	<h1>This is home page</h1>
	<p>Hello Everyone</p>

</body>
</html>