project/socialmediaplatform/media/urls.py
from django.urls import path
from . import views

urlpatterns=[

	# home route
	path('',views.home,name="home"),

	# authentication routes
	path("login/",views.LoginView,name="login"),
	path("signup/",views.SignupView,name="signup"),
	path("logout/",views.LogoutView,name="logout"),

	# post related routes
	path("like/<int:post_id>/",views.LikeView,name="like"),
	path("comment/<int:post_id>/",views.CommentView,name="comment"),
	path("commentslookup/<int:post_id>/",views.CommentLookupView,name="comments"),
	path("createpost/",views.CreatePostView,name="createpost"),
	path("deletepost/<int:post_id>/",views.DeletePostView,name="deletepost"),

	# friend request related routes
	path("sendrequest/<int:receiver_id>/",views.SendRequestView,name="sendrequest"),
	path("acceptrequest/<int:sender_id>/",views.AcceptRequestView,name="acceptrequest"),
	path("friendrequest/",views.FriendRequestView,name="friendrequest"),
]

project/socialmediaplatform/socialmediaplatform/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social/',include('media.urls')),
    # path("accounts/",include("django.contrib.auth.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/socialmediaplatform/media/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, related_name='friend_requests_sent', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='friend_requests_received', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

project/socialmediaplatform/media/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import UserProfile,Post,Comment
from django.contrib.auth.models import User

class UserProfileForm(UserCreationForm):
    bio = forms.CharField(max_length=500, required=False)
    profile_picture = forms.ImageField(required=False)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.save()

        bio = self.cleaned_data.get('bio')
        profile_picture = self.cleaned_data.get('profile_picture')

        UserProfile.objects.create(user=user, bio=bio, profile_picture=profile_picture)

        return user

class CreatePostForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=["content"]

class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment
		fields=["content"]

project/socialmediaplatform/media/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from .forms import UserProfileForm,CreatePostForm,CommentForm
from django.contrib.auth import login,authenticate,logout
from .models import Post,Like,FriendRequest,UserProfile,Comment
from django.contrib.auth.models import User

# Create your views here.
def home(request):
	posts=Post.objects.all()
	form=CommentForm()
	return render(request,"home.html",{"posts":posts,"form":form})

def LoginView(request):
	if request.method=="POST":
		form=AuthenticationForm(request,data=request.POST)
		if form.is_valid():
			username=form.cleaned_data["username"]
			password=form.cleaned_data["password"]
			user=authenticate(username=username,password=password)
			if user is not None:
				login(request,user)
				return redirect("home")
	else:
		form=AuthenticationForm()
	return render(request,"login.html",{"form":form})

def SignupView(request):
	if request.method=="POST":
		form=UserProfileForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect('login')
	else:
		form=UserProfileForm()
	return render(request,"signup.html",{"form":form})

def LogoutView(request):
	logout(request)
	return redirect("home")

def LikeView(request,post_id):
	user=request.user
	post=get_object_or_404(Post,id=post_id)
	like,created=Like.objects.get_or_create(user=user,post=post)
	if not created:
		like.delete()
	return redirect("home")

def CommentView(request,post_id):
	user=request.user
	post=Post.objects.get(id=post_id)
	if request.method=="POST":
		form=CommentForm(request.POST)
		if form.is_valid():
			form=form.save(commit=False)
			form.post=post
			form.user=user
			form.save()
			return redirect("home")

def CommentLookupView(request,post_id):
	post=Post.objects.get(id=post_id)
	comments=Comment.objects.filter(post=post)
	return render(request,"comments.html",{"comments":comments})

def CreatePostView(request):
	if request.method=="POST":
		form=CreatePostForm(request.POST)
		if form.is_valid():
			form=form.save(commit=False)
			form.user=request.user
			form.save()
			return redirect("home")
	else:
		form=CreatePostForm()
	return render(request,"createpost.html",{"form":form})

def DeletePostView(request,post_id):
	post=Post.objects.get(id=post_id)
	post.delete()
	return redirect("home")

def SendRequestView(request,receiver_id):
	from_user=request.user
	to_user=User.objects.get(id=receiver_id)
	FriendRequest.objects.create(from_user=from_user,to_user=to_user)
	return redirect("home")

def AcceptRequestView(request,sender_id):
	from_user=User.objects.get(id=sender_id)
	request=FriendRequest.objects.get(to_user=request.user,from_user=from_user)
	request.accepted=True
	request.save()
	return redirect("friendrequest")


def FriendRequestView(request):
	requests=FriendRequest.objects.filter(to_user=request.user)
	user=User.objects.all()
	return render(request,"friendrequest.html",{"user":user,"requests":requests})

project/socialmediaplatform/media/templates/baselayout.html
<!DOCTYPE html>
<html>
<head>
	<title>SOCIVIBE</title>
	<script src="https://cdn.tailwindcss.com"></script>
</head>
{% if request.user.is_authenticated %}
<body>
	<nav class="flex justify-between bg-gradient-to-r from-green-500 to-yellow-500 font-bold tracking-widest text-lg rounded-xl">
		<div class="container mx-auto flex justify-between items-center">
        <!-- Logo -->
        <a href="{% url 'home' %}" class="text-white text-xl font-bold"><img src="/static/media/logo.png" class="h-12 w-24 p-1"></a>

        <!-- Navigation Links -->
        <div class="space-x-4">
	        <a href="{% url 'friendrequest'%}" class="hover:text-blue-600">friend requests</a>
			<a href="{% url 'createpost' %}" class="hover:text-blue-600">Createpost</a>
			<a href="{% url 'logout' %}" class="hover:text-blue-600">logout</a>
		</div>
    </div>
	</nav>
{% else %}
<body class="bg-[url('/static/media/background.jpg')] bg-cover">
	<nav class="flex justify-between bg-gradient-to-r from-green-500 to-yellow-500 font-bold tracking-widest text-lg rounded-xl">
		<div class="container mx-auto flex justify-between items-center">
	        <!-- Logo -->
	        <a href="{% url 'home' %}" class="text-white text-xl font-bold"><img src="/static/media/logo.png" class="h-12 w-24 p-1"></a>

	        <!-- Navigation Links -->
	        <div class="space-x-4">
		        <a href="{% url 'login' %}" class="hover:text-blue-600">login</a>
				<a href="{% url 'signup' %}" class="hover:text-blue-600">signup</a>
			</div>
    	</div>
    </nav>

{% endif %}
	{% block content %}
	{% endblock %}
	<footer class="fixed bottom-0 w-10/12 h-8 bg-gradient-to-r from-green-500 to-yellow-500 text-center font-bold tracking-widest text-lg rounded-xl ml-32 mb-1">
		<h1 class="text-center">©Socivibe.org</h1>
	</footer>
</body>
</html>

project/socialmediaplatform/media/templates/comments.html
{% extends 'baselayout.html' %}
{% block content %}
{% for comment in comments %}
	<h4 class="font-bold text-2xl">{{ comment.user}}</h4>
	<p>{{ comment.content }}</p>
	<p>{{ comment.created_at }}</p>
{% endfor %}
{% endblock %}

project/socialmediaplatform/media/templates/createpost.html
{% extends 'baselayout.html' %}
{% block content %}
<div class="flex items-center justify-center mt-36">
		<div class="bg-blue-500 p-8 rounded-md shadow-md">
		    <form method="POST" action="{% url 'createpost' %}" class="flex flex-col w-96 pt-8 pb-8">
		    	<h1 class="text-center uppercase font-bold text-xl">Create Post</h1>
				{% csrf_token %}
				{{form}}
				<button type="submit" class="mt-6 bg-yellow-400 max-w-24 ml-36 p-2 rounded-full hover:bg-blue-300 hover:rounded-lg">submit</button>
			</form>
		</div>
	</div>
{% endblock %}

project/socialmediaplatform/media/templates/friendrequest.html
{% extends 'baselayout.html' %}
{% block content %}
  <h2>Friend Requests</h2>

  <h3>Received Requests:</h3>
  <ul>
    {% for request in requests %}
      {% if request.accepted == False %}
      <li>
        {{ request.from_user.username }} 
        <form method="post" action="{% url 'acceptrequest' request.id %}">
          {% csrf_token %}
          <button type="submit">Accept</button>
        </form>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
    <h3>Reccomendation:</h3>
    {% for u in user %}
    <p>{{u.username}}</p>
    <a href="{% url 'sendrequest' u.id %}">send request</a>
    {% endfor %}
{% endblock %}

project/socialmediaplatform/media/templates/home.html
{% extends 'baselayout.html' %}
{%block content %}
 <style>
        textarea {
            height:30px;
        }
    </style>
{% if request.user.is_authenticated %}
<h1>Hello {{request.user}}</h1>
{% for post in posts %}
	<div class="flex items-center justify-center mt-2">
		<div class="bg-blue-500 p-8 rounded-md shadow-md">
			{% if post.user.userprofile.profile_picture %}
			    <img src="{{post.user.userprofile.profile_picture.url}}" alt="Profile Picture" class="h-12 p-1 rounded-full">{{post.user}}--{{post.created_at}}
			{% else %}
			    <!-- Display a default image or alternative content if no profile picture is available -->
			    <p><img src="/static/media/default.jpg" alt="Default Image" class="h-12 p-1 rounded-full">{{post.user}}--{{post.created_at}}</p>
			{% endif %}
			{% if request.user == post.user %}
			<form method="POST" action="{% url 'deletepost' post.id %}">
		            {% csrf_token %}
		            <input type="submit" value="Delete" class="hover:font-bold">
		    </form>
		    {% endif %}
			<p>{{post.content}}</p>
			<form method="POST" action="{% url 'like' post.id %}">
		            {% csrf_token %}
		            <input type="submit" value="Like" class="hover:font-bold">--{{post.like_set.count}}
		    </form>
		   
		    <form method="POST" action="{% url 'comment' post.id %}">
		            {% csrf_token %}
		            {{form}}
		            <input type="submit" value="Comment" class="hover:font-bold">
		    </form>
		    <a href="{% url 'comments' post.id %}" class="hover:font-bold">comments</a>
		</div>
	</div>
{% endfor %}
{% endif %}
{% endblock %}

project/socialmediaplatform/media/templates/login.html
{% extends 'baselayout.html' %}
{% block content %}
<div class="flex items-center justify-center mt-36">
		<div class="bg-blue-500 p-8 rounded-md shadow-md">
		    <form method="POST" action="{% url 'login' %}" class="flex flex-col w-96 pt-8 pb-8">
		    	<h1 class="text-center uppercase font-bold text-xl">login</h1>
				{% csrf_token %}
				{{form}}
				<button type="submit" class="mt-6 bg-yellow-400 max-w-24 ml-36 p-2 rounded-full hover:bg-blue-300 hover:rounded-lg">submit</button>
			</form>
		</div>
	</div>
{% endblock %}

project/socialmediaplatform/media/templates/signup.html
{% extends 'baselayout.html' %}
{% block content %}
<div class="flex items-center justify-center pt-4">
		<div class="bg-blue-500 p-8 rounded-md shadow-md">
		    <form method="POST" action="{% url 'signup' %}" class="flex flex-col w-96 pt-2 pb-2">
		    	<h1 class="text-center uppercase font-bold text-xl">signup</h1>
				{% csrf_token %}
				{{form}}
				<button type="submit" class="mt-6 bg-yellow-400 max-w-24 ml-36 p-2 rounded-full hover:bg-blue-300 hover:rounded-lg">submit</button>
			</form>
		</div>
{% endblock %}